package com.mentorondemand.userservice.controllers;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.mentorondemand.userservice.entities.Technologies;
import com.mentorondemand.userservice.services.TechnologyRepository;

@RestController
@CrossOrigin(origins = "http://111.231.63.123:4200")
@RequestMapping(path = "/v1/tech")
public class TechnologyController {
	@Autowired // This means to get the bean called technologyRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private TechnologyRepository technologyRepository;

	@PostMapping(path = "/add")
	public @ResponseBody Object addTech(@Valid @RequestBody Technologies tech) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		return technologyRepository.save(tech);
	}

	@DeleteMapping(path = "/remove/{skillName}")
	public @ResponseBody Object removeTech(@PathVariable(value = "skillName") String skillName) {
		return technologyRepository.deleteBySkillName(skillName);
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<Technologies> getAllTechnologies() {
		// This returns a JSON or XML with the users
		return technologyRepository.findAll();
	}
}
